Repository Educational-Websites/JS-Tutorials, pull requests merged in 2021-08, with the labels that each got.

#66 Add files via upload
  bg.jpg
Labels: invalid

#98 Remove "Hello World," from meta keywords
  index.html
Labels: documentation, enhancement, Priority: 3

#99 Make errors.html
  alerts.html
  copyright.html
  errors.html
Labels: enhancement, New Tutorial, Repository Related

#113 Add If loops and prompts
  conditional_loops.html
  copyright.html
  errors.html
  index.html
  prompts.html
Labels: enhancement, New Tutorial, Repository Related
